### ISSUE TITLE
Add metadata to models

### ISSUE THREAD

**Issue by rernst** [UMCUGenetics/ExonCov#23]
### Label based
- Sample
  - Type (WES + Enrichment / WGS)
- Sequencing run
  - Sequencer (nextseq / novaseq)
  - Flowcell
- Analysis project
  - Type (Dx Production (empty) / Dx Validation / Research project)

### Panel / Panel version:
- Coverage requirement cutoff (15x)
- Disease description (Dutch and English?)
- Helix Ind
- Panel comments / notes
- patientfolder Cartagenia/Alissa
- Clinic contact -> Klin Gen + A(N)IOS
- Staflid

**Comment by hwmvandeutekom** [comment]
A(N)IOS / Klin Gen / Staflid: wel als metadata; de data in de verrichtingentabel is outdated
