### ISSUE TITLE
Create easy way to check coverage of a single gene

### ISSUE THREAD

**Issue by hwmvandeutekom** [UMCUGenetics/ExonCov#24]
When asked for a coverage, one needs to make a custom panel with one gene to see its coverage. Often these questions are asked while on the phone, so it would be fantastic when there is an easy way to do this.

**Comment by rernst** [comment]
How traceable should this be and for what reason will it be used? The whole point of custom panels is to make sure we can trace back what genes have been looked at, in combination with a 'Test reference number'.

**Comment by hwmvandeutekom** [comment]
Just to inform the applicant (geneticist) to say something about coverage. Often on the phone (hence need for a fast way to do this). No need for traceability.  Thus, could be a gene list with the min,median,max coverage of 100 random genes.
